name: flutter_date_formatter
description: A Flutter package for formatting dates and times in various locales. This package provides utilities for formatting relative dates, ordinal numbers, and more.
version: 0.0.9
homepage: https://github.com/thanhhaidev/flutter_date_formatter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ">=0.19.0 <0.21.0"

dev_dependencies:
  test: ^1.25.15
  very_good_analysis: ^7.0.0
